FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json  ./
RUN npm run

COPY apps ./apps
COPY packages  ./packages

RUN npm install 

RUN npm run prisma:generate


CMD ["npm", "run" , "start-withdraw-app"]