FROM node:20.17.0-alpine

WORKDIR /user/src/app

COPY package.json package-lock.json turbo.json  ./


COPY apps ./apps
COPY packages  ./packages

RUN npm install 

RUN npm run prisma:generate

RUN npm run build

EXPOSE 3000

# Make sure your start script binds to 0.0.0.0
CMD ["npm" , "run" , "start-user-app"]