FROM node:20.12.0-alpine3.19

WORKDIR /user/src/app

# Copy everything first (important for monorepos)
COPY . .

# Install dependencies
RUN npm install

# Generate Prisma client
RUN npm run prisma:generate

# Expose the port your app uses
EXPOSE 3004

# Start your withdraw app
CMD ["npm", "run", "deposit"]
