FROM node:20.12.0-alpine3.19

# Create and set working directory
WORKDIR /user/src/app

# Copy dependency manifests
COPY package.json package-lock.json turbo.json ./

# Install dependencies early to cache layers
RUN npm install

# Copy application code
COPY apps ./apps
COPY packages ./packages

# Generate Prisma client
RUN npm run prisma:generate

# Expose port for external access
EXPOSE 3004

# Start the deposit server
CMD ["npm", "run", "deposit"]
