import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "../lib/providers";
import ReactQueryProvider from "../lib/react-query-provider";
import LoadingBar from "./loading-bar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Paytm",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <Providers>
       
        <LoadingBar/>
        <ReactQueryProvider>

        {children}
        </ReactQueryProvider>
     
          {/* <AppBar></AppBar> */}
        </Providers>
      </body>
    </html>
  );
}
