name: Build on PR

on: 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on:  ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: User Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install Depndency
        run: npm  install
      
      - name: Run Build
        run : npm run build
    