name: Build and Deploy to docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on:  ubuntu-latest
    steps:
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: log in docker Hub
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build and push to dockerhub
        uses: docker/build-push-action@v2
      
        with:
          context: .
          file: ./Docker/Dockerfile.user
          push: true
          tags: ranjitdas2048/ewallet:v1
      
      - name: Verify push image
        run: docker pull ranjitdas2048/ewallet:v1
      